name: Cross-Platform Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.2.3

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
        include:
          - os: js
            arch: wasm
            is_wasm: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run formatting checks
        run: make fmt && make vet

      - name: Run tests
        run: make test

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build binary
        if: ${{ !matrix.is_wasm }}
        run: |
          EXT=""
          if [[ "${{ matrix.os }}" == "windows" ]]; then EXT=".exe"; fi
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/pir-${{ matrix.os }}-${{ matrix.arch }}$EXT ./cmd

      - name: Build WASM binary
        if: ${{ matrix.is_wasm }}
        run: |
          GOOS=js GOARCH=wasm go build -o dist/pir-wasm.wasm ./cmd

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*

